# Generated by Django 3.0.14 on 2021-12-03 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeGame',
        ),
    ]
