# Generated by Django 3.0.14 on 2021-12-03 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_delete_typegame'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameWordMemoryCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='TypeGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ImageOfGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='game/img/')),
                ('word_memory_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.GameWordMemoryCards')),
            ],
        ),
        migrations.AddField(
            model_name='gamewordmemorycards',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.TypeGame'),
        ),
    ]
