# Generated by Django 3.0.14 on 2021-12-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_gamegoldenfish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageofgame',
            name='word_memory_card',
        ),
        migrations.AddField(
            model_name='gamewordmemorycards',
            name='imgs',
            field=models.ManyToManyField(to='course.ImageOfGame'),
        ),
    ]
