# Generated by Django 3.0.14 on 2022-01-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20211231_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_banner',
            field=models.ImageField(upload_to='course/banner_detail/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.ImageField(upload_to='course/banner/'),
        ),
    ]
