# Generated by Django 3.0.14 on 2022-01-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=55)),
                ('email', models.EmailField(max_length=55)),
                ('phone', models.CharField(default='', max_length=11)),
                ('address', models.TextField(default='', max_length=255)),
                ('content', models.TextField(default='', max_length=255)),
            ],
        ),
    ]
