# Generated by Django 3.0.14 on 2021-12-11 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0004_gamegoldenfish'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('max_quantity_user', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RoomCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_room', models.CharField(max_length=30, unique=True)),
                ('is_private', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Phòng chờ'), (1, 'Phòng riêng'), (2, 'Đang thi')], default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('type_compete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.TypeCompetition')),
                ('user_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_host', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, help_text='users who are connect to the competition', related_name='list_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
