# Generated by Django 3.0.14 on 2021-12-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_auto_20211212_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typecompetition',
            old_name='max_quantity_user',
            new_name='max_quantity_add_user',
        ),
    ]
