# Generated by Django 3.0.14 on 2021-12-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_auto_20211212_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcompetition',
            name='skills',
            field=models.CharField(choices=[('Tổng hợp', 'Từ vựng - ngữ pháp - nghe & đọc hiểu')], default='Tổng hợp', max_length=70),
        ),
    ]
