# Generated by Django 3.0.14 on 2021-11-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermember', '0003_auto_20211126_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_student',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
