# Generated by Django 3.0.14 on 2021-12-04 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20211203_2230'),
        ('usermember', '0005_auto_20211128_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorestudent',
            name='type_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.TypeGame'),
        ),
        migrations.DeleteModel(
            name='detailStudent',
        ),
    ]
