# Generated by Django 3.0.14 on 2021-12-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermember', '0007_auto_20211231_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.TextField(default='', max_length=150),
        ),
    ]
