# Generated by Django 3.0.14 on 2021-12-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermember', '0009_auto_20211231_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='link_video',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
