# Generated by Django 3.0.14 on 2022-01-01 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermember', '0010_auto_20211231_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='coefficients_salary',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(12.0)]),
        ),
    ]
