# Generated by Django 3.0.14 on 2022-01-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermember', '0014_auto_20220110_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='std_img',
            field=models.ImageField(default='../static/img/noavatar.gif', upload_to='user/image-student/'),
        ),
    ]
